### ISSUE TITLE
Any example working game using this template system?

### ISSUE THREAD

**Issue by budda** [rblopes/generator-phaser-plus#18]
Do you have any repository demonstrating a game in some working form using the layout pattern proposed by this generator - would be a nice example guide for n00bs.

**Comment by rblopes** [comment]
Nope. At least, not an up-to-date example, I'm afraid.
Perhaps my frustrated attempt at porting [Heart Star](https://github.com/rblopes/heart-star), but I modified it in so many ways, it's not the best one.

**Comment by budda** [comment]
I loved the Heart Star game concept. Had a look at your version on GitHub before posting but it didn't seem to follow your generator pattern for laying out the game so much.

Gotta eat your own dog food as they say! 😄

**Comment by rblopes** [comment]
Like I said before, it's not best or most up-to-date example. Actually, I'm cheating a little here, because this game project began months before slush-phaser-plus, but I extracted the template game project (that became phaser-plus-template) a few days later.

Meanwhile, the game project was updated several times, for improvements on the game as well the project structure, sharing code from the master template, but stopped eventually. That project and all stuff that came after this are somehow related. Many ideas, good and bad, came from this project (and also from several other scrapped game projects too).

I have a few ideas for a demo game, but there is no priority for such a project at the moment, not before I finish some more demanding tasks at least.
