### ISSUE TITLE
Adding more distribution packaging options for build

### ISSUE THREAD

**Issue by budda** [rblopes/generator-phaser-plus#19]
How about adding support for exporting a project as a package for http://electron.atom.io/ using the gulp dist: task ?

And similar for things like Cordova ? (if already installed on system)

**Comment by rblopes** [comment]
Well, that's a problem, because I want to these too! But that raises some questions. Should I go with Electron or make the template compatible with a Cordova/PhoneGap workflow? I can't choose both, each one requires different setups and have different goals. It's tempting to choose one and neglect the potential of the other, but maintaining the two is difficult enough.

Unfortunately, I can't stand with one at the moment. As I've messed with this project a few times already (yep!), right now I'm deciding the final details to what will become version 1.0 of the generator, only major issue holding me back (I haven't forgotten!) is the documentation I failed to deliver two times (or more?).

After fulfilling this step, it will take me some time to evaluate options. Of course, I'm more inclined to choose Cordova, but I'll need some help to get things done here, so everyone can enjoy creating games for mobile devices without much hassle. I'll let everyone know when time comes.

**Comment by budda** [comment]
I believe Cordova/Phonegap and Electron are two completely different things -- so no need to choose one!

Electron for creating desktop games.
Cordova for mobile games.

**Comment by budda** [comment]
I had a crack and got my head around Electron this evening packaging up for all desktop platforms based on a Phaser game using this generator.

Would you be interested in a pull request with an initial stab at adding Electron distribution capabilities ?

**Comment by rblopes** [comment]
@budda, I really appreciate your effort there. Please, feel free to do so using the template repository then, since it is an already working implementation and easier to make and verify changes there. There is no guarantee that I'll include this feature in the next release, though.

Now, of course I could try and offer both Electron and Cordova templates, but that would become a big headache for me.

Firstly, maintenance and structuring of the generator would become a big mess. I know implementing Electron isn't that hard at all, but Cordova itself has its own requirements and issues, and combining both setups is a worthless challenge. It would be better to split the generator in two then, but that leads to another problem.

Ensuring templates are working and up-to-date is a bit time consuming. Remember that I run this project in my spare time, and I have been doing only maintenance updates until recently. Of course, contributions are very welcome, but for some, I'll need to establish some guidelines first so everyone can benefit.

Don't get me wrong. Like I said before, I want to offer Cordova (and perhaps Electron) support too, it's an outstanding feature to have, I'm in for that. I just don't feel this is the right moment though, specially now that I'm about to finish introducing several changes to this project, changes I've been planning for during the last month and half. There are good reasons I'm not disclosing all details here, however.

For now, I'm closing the issue, but I may bring it back another time when the last details have been resolved.
