### ISSUE TITLE
Development guide link is broken

### ISSUE THREAD

**Issue by disperse** [rblopes/generator-phaser-plus#25]
Link in README.md is broken:

https://github.com/rblopes/generator-phaser-plus/blob/master/docs/dev-guide.md

**Comment by rblopes** [comment]
Sorry about that. I'm still working on the development guide. When complete, it should serve as a small reference for contributors regarding the generator development and its companion template projects. Because of some changes made recently to the repository, and my little time to spare on the project at the moment, I'm afraid it'll take a bit longer than planned to complete.

If you're actually looking for the regular manual pages, the `v2.x` branch contains a [snapshot of the manual](https://github.com/rblopes/generator-phaser-plus/tree/v2.x/docs) for the latest stable version. The ones you see in the `master` branch are about to change and should be revised for v3 in the near future.

**Comment by disperse** [comment]
Thanks! I was interested in what sub-generators were included and see this is documented in the v2.x branch you linked.
